api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /ecommerce/api/v1
    # defaults:
    #     _format: json

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /ecommerce/api/v1/login_check
