api:
    resource: "@ApiBundle/Controller/"
    # type:     annotation
    prefix:   /api/v1/
    # defaults:
    #     _format: json

api_product_index:
    path: /api/v1/products
    defaults: { _controller: ApiBundle:Product:index}
    methods:  [GET]

product_get_action:
    path: /api/v1/products/{id}
    defaults: { _controller: ApiBundle:Product:get}
    methods:  [GET]

product_save:
    path: /api/v1/products
    defaults: { _controller: ApiBundle:Product:save}
    methods:  [POST]

app:
    resource: '@AppBundle/Controller/'
    type: annotation
