<?php

namespace ApiBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCategories($search = '')
    {
        $queryBuilder = $this->createQueryBuilder('c');

        if ($search) {
            $queryBuilder->andWhere('c.name LIKE :search')
                ->setParameter('search', '%' . $search . '%');
        }

        return $queryBuilder;
    }
}
